## NUMPYS 

Numpy is a fundamental package for scientific computing and for manipulation of multimedia dimensional arrays and matrices. 


In [1]:
import numpy 

import numpy as np 


In [3]:
#creatinga1darray 
x=np.array([1, 2, 3, 4, 5])
y= np.array([9, 10])

print(x)
print('The shape of x is', x.shape)

print(y)
print('The shape of y is', y.shape)


[1 2 3 4 5]
The shape of x is (5,)
[ 9 10]
The shape of y is (2,)


In [6]:
#2DArrays 
z= np.array([[1,2],[3,4]])
print(z)
print('The shape of z is', z.shape)


[[1 2]
 [3 4]]
The shape of z is (2, 2)


In [10]:
#multipledimensionarray
w=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(w, '/n')
print('The shape of w is', w.shape)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] /n
The shape of w is (3, 3, 3)


## NUMPY FUNCTIONS 
arange 
reshape
zeroes 
one
full
linspace 
random
arange 


In [12]:
#Arange
#creates a 1d array with 10 elements in it
A10=np.arange(10)
A10
print(A10)


[0 1 2 3 4 5 6 7 8 9]


In [16]:
#Reshape

B10=A10.reshape(-1,1)
print (A10,'\n', B10)
print('The shape of array X =', B10.shape)


[0 1 2 3 4 5 6 7 8 9] 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
The shape of array X = (10, 1)


In [18]:
A10 = B10.reshape(2,5)

print(A10)
print('The shape of 1D array x=', A10.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
The shape of 1D array x= (2, 5)


In [21]:
#zeroes is used to create ana array filled with zeroes
np_zeros= np.zeros((2,3))
np_zeros


array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
#zeroes is used to create ana array filled with zeroes
np_zeros= np.zeros((2,3))
np_zeros.astype(int)


array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
np_ones= np.ones((2,3))

np_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np_full = np.full((2,3), 4)
np_full

array([[4, 4, 4],
       [4, 4, 4]])

In [25]:
np_eye = np.eye(6,6)

np_eye

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [27]:
#linspace returns evenly spaced nunbers over a specified amount
np_linspace = np.linspace(0, 10, num=6)

np_linspace

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [28]:
#linspace returns evenly spaced nunbers over a specified amount
np_linspace = np.linspace(0, 10, num=5)

np_linspace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
#RAND: this creates an array filled with random values between 0 and 1

np_rand= np.random.random_sample((2,3))

np_rand1 = np.random.rand(2,3)

X=np.random.randint(10, size=(5,3))
np.save('array_data.npy',np_rand)
print(np_rand)

print(np_rand1)
X


[[0.94600108 0.26246822 0.10858844]
 [0.84149147 0.57396799 0.78668537]]
[[0.89260265 0.54030513 0.74505021]
 [0.70066117 0.13517461 0.39343691]]


array([[2, 0, 6],
       [7, 4, 4],
       [1, 7, 3],
       [5, 3, 4],
       [8, 5, 0]])

## Accessing Elements of Numpy Array

To do this in a 2d array you must specify an index for both the row and the column

In [43]:
#Row 1, column 0 gives a scalar
print(z)
z[1,1]

[[1 2]
 [3 4]]


4

In [48]:
p=np.array([[1,2],[3,4]])
print(p)

[[1 2]
 [3 4]]


In [44]:
#ar

p= z[1][0]
p

3

In [45]:
p=(z[0:1, 0])
p

array([1])

## Numpy Attributes

In [51]:
print('The Dtype of elements in array X= ', x.dtype)

print('The shape of ND array W= ', w.dtype)

The Dtype of elements in array X=  int32
The shape of ND array W=  int32


In [53]:
print('The shape of 1D array X= ', x.shape)
print('The shape of 2D array Z= ', z.shape)
print('The shape of ND array W= ', w.shape)
print('The shape of arange A10= ', A10.shape)

The shape of 1D array X=  (5,)
The shape of 2D array Z=  (2, 2)
The shape of ND array W=  (3, 3, 3)
The shape of arange A10=  (2, 5)


In [54]:
print('The shape of ND array W= ', w.size)
print('The shape ofarange A10= ', A10.size)

The shape of ND array W=  27
The shape ofarange A10=  10


## Numpy Array Math Operations


In [56]:
x= np.array([[1,2,3],[4,5,6]])
y= np.array([[2,2,2],[3,3,3]])
z= np.array([1,2,3])

In [57]:
#Transpose
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])